version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_DB: bookingsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-network

    # Redis Server
  redis:
    image: redis:7
    container_name: booking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - booking-network


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  booking-network:
    driver: bridge