--
-- PostgreSQL database dump
--

-- Dumped from database version 13.6
-- Dumped by pg_dump version 13.6

-- Started on 2025-09-12 14:32:00 +07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 201 (class 1259 OID 49455)
-- Name: booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking (
    id integer NOT NULL,
    booking_date date,
    booking_status character varying(255),
    created_at timestamp(6) without time zone,
    class_id integer NOT NULL,
    user_id integer NOT NULL,
    user_purchase_id integer NOT NULL,
    CONSTRAINT booking_booking_status_check CHECK (((booking_status)::text = ANY ((ARRAY['CONFIRMED'::character varying, 'CANCELLED'::character varying, 'ATTENDED'::character varying])::text[])))
);


ALTER TABLE public.booking OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 49453)
-- Name: booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 49463)
-- Name: classes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.classes (
    id integer NOT NULL,
    class_name character varying(255),
    course_duration integer,
    created_at timestamp(6) without time zone,
    end_time time(6) without time zone,
    is_completed boolean,
    max_capacity integer,
    required_credits integer,
    start_time time(6) without time zone,
    country_id integer NOT NULL
);


ALTER TABLE public.classes OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 49461)
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 49470)
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id integer NOT NULL,
    code character varying(255),
    created_at timestamp(6) without time zone,
    currency character varying(255),
    name character varying(255)
);


ALTER TABLE public.country OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 49468)
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 49480)
-- Name: packages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.packages (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    credits integer NOT NULL,
    expired_date date,
    is_active boolean,
    package_name character varying(255),
    prices numeric(38,2),
    status character varying(255),
    country_id integer NOT NULL
);


ALTER TABLE public.packages OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 49478)
-- Name: packages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 49490)
-- Name: user_purchases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_purchases (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    expired_date date,
    purchase_status character varying(255),
    purchased_date date,
    package_id integer NOT NULL,
    user_id integer NOT NULL,
    remaining_credits integer NOT NULL,
    CONSTRAINT user_purchases_purchase_status_check CHECK (((purchase_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXPIRED'::character varying, 'USED'::character varying])::text[])))
);


ALTER TABLE public.user_purchases OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 49488)
-- Name: user_purchases_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 49498)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    created_at date,
    email character varying(255) NOT NULL,
    is_active boolean,
    is_verified boolean,
    password character varying(255),
    user_name character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 49496)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 49573)
-- Name: waiting_lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.waiting_lists (
    id integer NOT NULL,
    action character varying(255),
    created_at timestamp(6) without time zone,
    deducted_credits integer,
    joined_date timestamp(6) without time zone,
    booking_id integer NOT NULL,
    class_id integer NOT NULL,
    user_id integer NOT NULL,
    user_purchase_id integer NOT NULL,
    CONSTRAINT waiting_lists_action_check CHECK (((action)::text = ANY ((ARRAY['WAITING'::character varying, 'JOINED'::character varying, 'CANCLED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.waiting_lists OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 49571)
-- Name: waiting_lists_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.waiting_lists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.waiting_lists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 49508)
-- Name: waiting_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.waiting_logs (
    id integer NOT NULL,
    action character varying(255),
    created_at timestamp(6) without time zone,
    deducted_credits integer,
    joined_date timestamp(6) without time zone,
    booking_id integer NOT NULL,
    user_id integer NOT NULL,
    class_id integer NOT NULL,
    user_purchase_id integer NOT NULL,
    CONSTRAINT waiting_logs_action_check CHECK (((action)::text = ANY ((ARRAY['WAITING'::character varying, 'JOINED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.waiting_logs OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 49506)
-- Name: waiting_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.waiting_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.waiting_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3080 (class 2606 OID 49460)
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (id);


--
-- TOC entry 3082 (class 2606 OID 49467)
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- TOC entry 3084 (class 2606 OID 49477)
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- TOC entry 3086 (class 2606 OID 49487)
-- Name: packages packages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT packages_pkey PRIMARY KEY (id);


--
-- TOC entry 3090 (class 2606 OID 49515)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 3088 (class 2606 OID 49495)
-- Name: user_purchases user_purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_purchases
    ADD CONSTRAINT user_purchases_pkey PRIMARY KEY (id);


--
-- TOC entry 3092 (class 2606 OID 49505)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3096 (class 2606 OID 49578)
-- Name: waiting_lists waiting_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_lists
    ADD CONSTRAINT waiting_lists_pkey PRIMARY KEY (id);


--
-- TOC entry 3094 (class 2606 OID 49513)
-- Name: waiting_logs waiting_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_logs
    ADD CONSTRAINT waiting_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 3103 (class 2606 OID 49546)
-- Name: user_purchases fk20msk76085re67ok6gaivbsxq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_purchases
    ADD CONSTRAINT fk20msk76085re67ok6gaivbsxq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3101 (class 2606 OID 49536)
-- Name: packages fk2mk29vqr3fgg4ldcux2wditq4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT fk2mk29vqr3fgg4ldcux2wditq4 FOREIGN KEY (country_id) REFERENCES public.country(id);


--
-- TOC entry 3105 (class 2606 OID 49556)
-- Name: waiting_logs fk5du38r7da63p5gfikw32wjb28; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_logs
    ADD CONSTRAINT fk5du38r7da63p5gfikw32wjb28 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3104 (class 2606 OID 49551)
-- Name: waiting_logs fk60gcc0g740ix6uo0milaur5ge; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_logs
    ADD CONSTRAINT fk60gcc0g740ix6uo0milaur5ge FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- TOC entry 3108 (class 2606 OID 49579)
-- Name: waiting_lists fk6e9qxu2f3agnmu8u52obb80x6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_lists
    ADD CONSTRAINT fk6e9qxu2f3agnmu8u52obb80x6 FOREIGN KEY (booking_id) REFERENCES public.booking(id);


--
-- TOC entry 3098 (class 2606 OID 49521)
-- Name: booking fk7udbel7q86k041591kj6lfmvw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fk7udbel7q86k041591kj6lfmvw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3111 (class 2606 OID 49594)
-- Name: waiting_lists fkbyroduisrfm1lhmbxraoqaq47; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_lists
    ADD CONSTRAINT fkbyroduisrfm1lhmbxraoqaq47 FOREIGN KEY (user_purchase_id) REFERENCES public.user_purchases(id);


--
-- TOC entry 3107 (class 2606 OID 49566)
-- Name: waiting_logs fkcrnj813496n3rtmuwq91cheos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_logs
    ADD CONSTRAINT fkcrnj813496n3rtmuwq91cheos FOREIGN KEY (user_purchase_id) REFERENCES public.user_purchases(id);


--
-- TOC entry 3102 (class 2606 OID 49541)
-- Name: user_purchases fkdeqbfitlttiorolm02vox6n60; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_purchases
    ADD CONSTRAINT fkdeqbfitlttiorolm02vox6n60 FOREIGN KEY (package_id) REFERENCES public.packages(id);


--
-- TOC entry 3099 (class 2606 OID 49526)
-- Name: booking fkee002nvk2rpy4miv2fmn201no; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkee002nvk2rpy4miv2fmn201no FOREIGN KEY (user_purchase_id) REFERENCES public.user_purchases(id);


--
-- TOC entry 3110 (class 2606 OID 49589)
-- Name: waiting_lists fkgrlimcki9biwijhk3nqh8ni9p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_lists
    ADD CONSTRAINT fkgrlimcki9biwijhk3nqh8ni9p FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3106 (class 2606 OID 49561)
-- Name: waiting_logs fkp19no7cmo14e07nistvubr3jw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_logs
    ADD CONSTRAINT fkp19no7cmo14e07nistvubr3jw FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- TOC entry 3109 (class 2606 OID 49584)
-- Name: waiting_lists fkqiltbu3u5o6x5ysiu2jj9nw7x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waiting_lists
    ADD CONSTRAINT fkqiltbu3u5o6x5ysiu2jj9nw7x FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- TOC entry 3097 (class 2606 OID 49516)
-- Name: booking fkr4077s8jhw53tim2ujqfpbnl9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkr4077s8jhw53tim2ujqfpbnl9 FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- TOC entry 3100 (class 2606 OID 49531)
-- Name: classes fksd0xv22w22lavabpakine33n0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT fksd0xv22w22lavabpakine33n0 FOREIGN KEY (country_id) REFERENCES public.country(id);


-- Completed on 2025-09-12 14:32:01 +07

--
-- PostgreSQL database dump complete
--

